### PR TITLE
Adding spanish translation

### PR DESCRIPTION
**Pull request by marcosantoniocaro**
This locale is from an earlier version of en.yml, so might be outdated, let me know if something is missing.

### CODE REVIEW

**Comment by mischa78** [comment]
Sorry for the late reply and thank you for your contribution. Could you also add the following Spanish translations?

- app/views/clipboard/_clipboard_empty.es.html.erb
- app/views/reset_password/_message.es.html.erb
- app/views/user_mailer/reset_password_email.es.text.erb
- app/views/user_mailer/share_link_email.es.text.erb
- app/views/user_mailer/signup_email.es.text.erb

**Comment by marcosantoniocaro** [comment]
Hi,
    I have committed those missing files,
Bests.

**Comment by mischa78** [comment]
That's great! I'll have a look and merge as soon as possible. Thank you!!

**Comment by mischa78** [comment]
Thanks @claudiocebpaz and @marcosantoniocaro!! I don't know Spanish so I can't judge which of your translations is better. I am using marcosantoniocaro's for now. Feel free to send another pull request if you see room for improvement.

**Pull request merged**
