### PR TITLE
Add localization for simplified Chinese

### PR DESCRIPTION
**Pull request by john-coding**

### CODE REVIEW

**Comment by mischa78** [comment]
Thank you! I will merge this as soon as I have time to have a look at it.

**Comment by mischa78** [comment]
I'm getting "translation missing" when there are validation errors. Could you fix that? Thanks!
screen shot 2015-07-16 at 01 20 45

**Comment by mischa78** [comment]
@john-coding I found the mistake and fixed it. I've your pull request. Thanks a lot!!

**Comment by john-coding** [comment]
Thanks, Mischa.  (That mistake of misalignment is a minor mystery since it does not appear in my pull-request. It looks like a mishap during the merge process. Whatever it is, it does not matter now since you have fixed that mistake.)

**Comment by john-coding** [comment]
I see. My bad. Thanks!

**Pull request merged**
